FROM rust:1-bookworm AS builder

WORKDIR /app
COPY . .
RUN cargo build --release

FROM debian:bookworm-slim

WORKDIR /app
COPY --from=builder /app/target/release/simpro-ingestion-service /app/simpro-ingestion-service

EXPOSE 3000

CMD ["./simpro-ingestion-service"]