// @generated by xtask. Do not edit by hand.

pub mod table {
// @generated automatically by Diesel CLI.

pub mod sql_types {
    #[derive(diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "job_type"))]
    pub struct JobType;

    #[derive(diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "schedule_type"))]
    pub struct ScheduleType;
}

diesel::table! {
    activities (id) {
        id -> Int8,
        name -> Text,
    }
}

diesel::table! {
    activity_schedules (schedule_id, activity_id) {
        activity_id -> Int8,
        schedule_id -> Int8,
    }
}

diesel::table! {
    company_customers (id) {
        company_name -> Text,
        id -> Int8,
    }
}

diesel::table! {
    cost_centers (id) {
        id -> Int8,
        name -> Text,
    }
}

diesel::table! {
    employees (id) {
        id -> Int8,
        name -> Text,
        position -> Text,
    }
}

diesel::table! {
    job_schedules (schedule_id, job_id, cost_center_id) {
        cost_center_id -> Int8,
        job_id -> Int8,
        schedule_id -> Int8,
    }
}

diesel::table! {
    job_statuses (id) {
        color -> Text,
        id -> Int8,
        name -> Text,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use super::sql_types::JobType;

    jobs (id) {
        customer_id -> Int8,
        date_modified -> Timestamptz,
        description -> Text,
        id -> Int8,
        job_type -> JobType,
        name -> Text,
        site_id -> Int8,
        stage -> Text,
        status_id -> Int8,
    }
}

diesel::table! {
    lead_schedules (schedule_id, lead_id) {
        lead_id -> Int8,
        schedule_id -> Int8,
    }
}

diesel::table! {
    leads (id) {
        id -> Int8,
        name -> Text,
    }
}

diesel::table! {
    quote_schedules (schedule_id, quote_id, cost_center_id) {
        cost_center_id -> Int8,
        quote_id -> Int8,
        schedule_id -> Int8,
    }
}

diesel::table! {
    quotes (id) {
        id -> Int8,
        name -> Text,
    }
}

diesel::table! {
    schedule_blocks (schedule_id, iso8601_start_time, iso8601_end_time) {
        iso8601_end_time -> Timestamptz,
        iso8601_start_time -> Timestamptz,
        schedule_id -> Int8,
        schedule_rate -> Int8,
    }
}

diesel::table! {
    schedule_rates (id) {
        id -> Int8,
        name -> Text,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use super::sql_types::ScheduleType;

    schedules (id) {
        date_modified -> Timestamptz,
        id -> Int8,
        notes -> Nullable<Text>,
        schedule_type -> ScheduleType,
        staff_id -> Int8,
    }
}

diesel::table! {
    sites (id) {
        address_address -> Nullable<Text>,
        address_city -> Nullable<Text>,
        address_country -> Nullable<Text>,
        address_postal_code -> Text,
        date_modified -> Nullable<Timestamptz>,
        id -> Int8,
    }
}

diesel::joinable!(activity_schedules -> activities (activity_id));
diesel::joinable!(activity_schedules -> schedules (schedule_id));
diesel::joinable!(job_schedules -> cost_centers (cost_center_id));
diesel::joinable!(job_schedules -> jobs (job_id));
diesel::joinable!(job_schedules -> schedules (schedule_id));
diesel::joinable!(jobs -> company_customers (customer_id));
diesel::joinable!(jobs -> job_statuses (status_id));
diesel::joinable!(jobs -> sites (site_id));
diesel::joinable!(lead_schedules -> leads (lead_id));
diesel::joinable!(lead_schedules -> schedules (schedule_id));
diesel::joinable!(quote_schedules -> cost_centers (cost_center_id));
diesel::joinable!(quote_schedules -> quotes (quote_id));
diesel::joinable!(quote_schedules -> schedules (schedule_id));
diesel::joinable!(schedule_blocks -> schedule_rates (schedule_rate));
diesel::joinable!(schedule_blocks -> schedules (schedule_id));
diesel::joinable!(schedules -> employees (staff_id));

diesel::allow_tables_to_appear_in_same_query!(
    activities,activity_schedules,company_customers,cost_centers,employees,job_schedules,job_statuses,jobs,lead_schedules,leads,quote_schedules,quotes,schedule_blocks,schedule_rates,schedules,sites,);

}

pub mod enums {
use diesel_derive_enum::DbEnum;

#[derive(Debug, Clone, Copy, PartialEq, Eq, DbEnum)]
#[ExistingTypePath = "crate::db::table::sql_types::JobType"]
#[DbValueStyle = "PascalCase"]
pub enum JobType {
    Project,
    Service,
    Prepaid,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, DbEnum)]
#[ExistingTypePath = "crate::db::table::sql_types::ScheduleType"]
#[DbValueStyle = "snake_case"]
pub enum ScheduleType {
    Lead,
    Quote,
    Job,
    Activity,
}


}

pub mod models {
// Read-only models
// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::db::table::*;

use chrono::DateTime;
use chrono::offset::Utc;
use diesel::prelude::*;
#[derive(Debug, Clone, Queryable, Selectable, Identifiable)]
#[diesel(table_name = activities)]
pub struct Activity {
    pub id: i64,
    pub name: String,
}

#[derive(Debug, Clone, Queryable, Selectable, Identifiable)]
#[diesel(primary_key(schedule_id, activity_id))]
#[diesel(table_name = activity_schedules)]
pub struct ActivitySchedule {
    pub activity_id: i64,
    pub schedule_id: i64,
}

#[derive(Debug, Clone, Queryable, Selectable, Identifiable)]
#[diesel(table_name = company_customers)]
pub struct CompanyCustomer {
    pub company_name: String,
    pub id: i64,
}

#[derive(Debug, Clone, Queryable, Selectable, Identifiable)]
#[diesel(table_name = cost_centers)]
pub struct CostCenter {
    pub id: i64,
    pub name: String,
}

#[derive(Debug, Clone, Queryable, Selectable, Identifiable)]
#[diesel(table_name = employees)]
pub struct Employee {
    pub id: i64,
    pub name: String,
    pub position: String,
}

#[derive(Debug, Clone, Queryable, Selectable, Identifiable)]
#[diesel(primary_key(schedule_id, job_id, cost_center_id))]
#[diesel(table_name = job_schedules)]
pub struct JobSchedule {
    pub cost_center_id: i64,
    pub job_id: i64,
    pub schedule_id: i64,
}

#[derive(Debug, Clone, Queryable, Selectable, Identifiable)]
#[diesel(table_name = job_statuses)]
pub struct JobStatuse {
    pub color: String,
    pub id: i64,
    pub name: String,
}

#[derive(Debug, Clone, Queryable, Selectable, Identifiable)]
#[diesel(table_name = jobs)]
pub struct Job {
    pub customer_id: i64,
    pub date_modified: DateTime<Utc>,
    pub description: String,
    pub id: i64,
    pub job_type: crate::db::enums::JobType,
    pub name: String,
    pub site_id: i64,
    pub stage: String,
    pub status_id: i64,
}

#[derive(Debug, Clone, Queryable, Selectable, Identifiable)]
#[diesel(primary_key(schedule_id, lead_id))]
#[diesel(table_name = lead_schedules)]
pub struct LeadSchedule {
    pub lead_id: i64,
    pub schedule_id: i64,
}

#[derive(Debug, Clone, Queryable, Selectable, Identifiable)]
#[diesel(table_name = leads)]
pub struct Lead {
    pub id: i64,
    pub name: String,
}

#[derive(Debug, Clone, Queryable, Selectable, Identifiable)]
#[diesel(primary_key(schedule_id, quote_id, cost_center_id))]
#[diesel(table_name = quote_schedules)]
pub struct QuoteSchedule {
    pub cost_center_id: i64,
    pub quote_id: i64,
    pub schedule_id: i64,
}

#[derive(Debug, Clone, Queryable, Selectable, Identifiable)]
#[diesel(table_name = quotes)]
pub struct Quote {
    pub id: i64,
    pub name: String,
}

#[derive(Debug, Clone, Queryable, Selectable, Identifiable)]
#[diesel(primary_key(schedule_id, iso8601_start_time, iso8601_end_time))]
#[diesel(table_name = schedule_blocks)]
pub struct ScheduleBlock {
    pub iso8601_end_time: DateTime<Utc>,
    pub iso8601_start_time: DateTime<Utc>,
    pub schedule_id: i64,
    pub schedule_rate: i64,
}

#[derive(Debug, Clone, Queryable, Selectable)]
#[diesel(table_name = schedule_rates)]
pub struct ScheduleRate {
    pub id: i64,
    pub name: String,
}

#[derive(Debug, Clone, Queryable, Selectable)]
#[diesel(table_name = schedules)]
pub struct Schedule {
    pub date_modified: DateTime<Utc>,
    pub id: i64,
    pub notes: Option<String>,
    pub schedule_type: crate::db::enums::ScheduleType,
    pub staff_id: i64,
}

#[derive(Debug, Clone, Queryable, Selectable)]
#[diesel(table_name = sites)]
pub struct Site {
    pub address_address: Option<String>,
    pub address_city: Option<String>,
    pub address_country: Option<String>,
    pub address_postal_code: String,
    pub date_modified: Option<DateTime<Utc>>,
    pub id: i64,
}


}

pub mod insertables {
// Write-only models
#![allow(unused)]
#![allow(clippy::all)]
use crate::db::table::*;
use chrono::DateTime;
use chrono::offset::Utc;
use diesel::prelude::*;
use diesel::prelude::*;
#[derive(Insertable)]
#[diesel(table_name = activities)]
pub struct NewActivity<'a> {
    pub id: i64,
    pub name: &'a str,
}
#[derive(Insertable)]
#[diesel(table_name = activity_schedules)]
pub struct NewActivitySchedule {
    pub activity_id: i64,
    pub schedule_id: i64,
}
#[derive(Insertable)]
#[diesel(table_name = company_customers)]
pub struct NewCompanyCustomer<'a> {
    pub company_name: &'a str,
    pub id: i64,
}
#[derive(Insertable)]
#[diesel(table_name = cost_centers)]
pub struct NewCostCenter<'a> {
    pub id: i64,
    pub name: &'a str,
}
#[derive(Insertable)]
#[diesel(table_name = employees)]
pub struct NewEmployee<'a> {
    pub id: i64,
    pub name: &'a str,
    pub position: &'a str,
}
#[derive(Insertable)]
#[diesel(table_name = job_schedules)]
pub struct NewJobSchedule {
    pub cost_center_id: i64,
    pub job_id: i64,
    pub schedule_id: i64,
}
#[derive(Insertable)]
#[diesel(table_name = job_statuses)]
pub struct NewJobStatuse<'a> {
    pub color: &'a str,
    pub id: i64,
    pub name: &'a str,
}
#[derive(Insertable)]
#[diesel(table_name = jobs)]
pub struct NewJob<'a> {
    pub customer_id: i64,
    pub date_modified: DateTime<Utc>,
    pub description: &'a str,
    pub id: i64,
    pub job_type: crate::db::enums::JobType,
    pub name: &'a str,
    pub site_id: i64,
    pub stage: &'a str,
    pub status_id: i64,
}
#[derive(Insertable)]
#[diesel(table_name = lead_schedules)]
pub struct NewLeadSchedule {
    pub lead_id: i64,
    pub schedule_id: i64,
}
#[derive(Insertable)]
#[diesel(table_name = leads)]
pub struct NewLead<'a> {
    pub id: i64,
    pub name: &'a str,
}
#[derive(Insertable)]
#[diesel(table_name = quote_schedules)]
pub struct NewQuoteSchedule {
    pub cost_center_id: i64,
    pub quote_id: i64,
    pub schedule_id: i64,
}
#[derive(Insertable)]
#[diesel(table_name = quotes)]
pub struct NewQuote<'a> {
    pub id: i64,
    pub name: &'a str,
}
#[derive(Insertable)]
#[diesel(table_name = schedule_blocks)]
pub struct NewScheduleBlock {
    pub iso8601_end_time: DateTime<Utc>,
    pub iso8601_start_time: DateTime<Utc>,
    pub schedule_id: i64,
    pub schedule_rate: i64,
}
#[derive(Insertable)]
#[diesel(table_name = schedule_rates)]
pub struct NewScheduleRate<'a> {
    pub id: i64,
    pub name: &'a str,
}
#[derive(Insertable)]
#[diesel(table_name = schedules)]
pub struct NewSchedule<'a> {
    pub date_modified: DateTime<Utc>,
    pub id: i64,
    pub notes: Option<&'a str>,
    pub schedule_type: crate::db::enums::ScheduleType,
    pub staff_id: i64,
}
#[derive(Insertable)]
#[diesel(table_name = sites)]
pub struct NewSite<'a> {
    pub address_address: Option<&'a str>,
    pub address_city: Option<&'a str>,
    pub address_country: Option<&'a str>,
    pub address_postal_code: &'a str,
    pub date_modified: Option<DateTime<Utc>>,
    pub id: i64,
}

}
